services:
  linkstack:
    hostname: 'linkstack'
    build:
      context: .
      args:
        VERSION: ${VERSION}
    volumes:
      # - ./env.docker:/var/www/html/env.docker
      - ./storage/:/app/storage"
    ports:
      - '8080:80'
    restart: unless-stopped
    depends_on:
      - db
    links:
      - db
  db:
    image: mariadb:12.3.2
    environment:
        MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
        MARIADB_DATABASE: ${DB_DATABASE}
        MARIADB_USER: ${DB_USERNAME}
        MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/:/var/lib/mysql"
